### PR TITLE
Dev branch merge ECResourceInfoRestfulAPI #4735

### PR DESCRIPTION
**Pull request by zhaowenkai111**
### What is the purpose of the change

修改两处语法错误的bug，分别位于 76行和 90 行，还原修改错误的 95 行。
image

### Related issues/PRs

Related issues: #4735 
Related pr:#4745

### Brief change log

- Define the core abstraction and interfaces of the EngineConn Factory;
- Define the core abstraction and interfaces of Executor Manager.

### Checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [Linkis mailing list](https://linkis.apache.org/community/how-to-subscribe) first)
- [ ] **If this is a code change**: I have written unit tests to fully verify the new behavior.

### CODE REVIEW

**Comment by zhaowenkai111** [comment]
for issue #4735

**Comment by zhaowenkai111** [comment]
change merge version from master to release  [apache:release-1.3.2](https://github.com/apache/linkis/tree/release-1.3.2)

**Review by zhaowenkai111 — COMMENTED** [review]
ok for change

**Comment by peacewong** [comment]
should submit to the master branch

**Pull request closed without merging**
