### PR TITLE
[ISSUES-1276]Upgrade some components of npm that the linkis console depends on

### PR DESCRIPTION
**Pull request by QuantumXiecao**
Upgrade some components of npm that the linkis console depends on

### What is the purpose of the change

Upgrade some components of npm that the linkis console depends on.

After fixing:
image
By the way
1: if developers encounter node-sass related problem when running npm install. It is likely to be the node version incompatibility. You can ajust node-sass version according to the following pic:
image
2: Please make sure java/scala/js pass the check rule. My last commit is because dev-1.3.2's DsmReceiver.scala has not been formatted properly and I have to regularize again.

@casionone @peacewong  
Can we upgrade FrontEnd CI/CD environment to nodeJS 16+? 
Some npm packages upgradation depends on higher version nodejs.
My PR depends on upgradation of CI/CD from node14.21.2 to node16+. 

### Related issues/PRs

Related issues: #1275
Related issues: #1276

### Brief change log

- Upgrade some components of npm that the linkis console depends on.
- Reformat code by eslint(Including console related problems).

### Checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [Linkis mailing list](https://linkis.apache.org/community/how-to-subscribe) first)
- [ ] **If this is a code change**: I have written unit tests to fully verify the new behavior.

### CODE REVIEW

**Comment by QuantumXiecao** [comment]
My PR depends on upgradation of CI/CD from node14.21.2 to node16+. Node16+ now is commonly used so could we please upgrade CI/CD node version?

**Comment by casionone** [comment]
Build Frontend failed
need to update  build action base on node 16?

**Comment by QuantumXiecao** [comment]
Thanks for your remind! I have ajusted build-frontend.yml from node14 to node16.

**Comment by QuantumXiecao** [comment]
Thanks for your remind! I have ajusted build-frontend.yml from node14 to node16.

**Review by det101 — COMMENTED** [review]
Check failure on line 445 in linkis-web/src/apps/linkis/module/ECM/index.vue

**Comment by QuantumXiecao** [comment]
I have missed some places. Thanks for your remind. @det101

**Review by det101 — APPROVED** [review]

**Pull request merged**
