### PR TITLE
Translate engineconn-plugins-presto service classes from Scala to Java

### PR DESCRIPTION
**Pull request by ChengJie1053**
What is the purpose of the change
1, Reduce scala modules in engineconn-plugins-presto module.
2,Optimize and remove some code
3, Translate engineconn-plugins-presto service classes from Scala to Java using Chatgpt.

Related issues: #4192

Brief change log
1, Reduce scala modules in engineconn-plugins-presto module.
2, Translate engineconn-plugins-presto service classes from Scala to Java using Chatgpt.
3, finish test engineconn-plugins-presto module

### CODE REVIEW

**Comment by peacewong** [comment]
pring @ChengJie1053 need to fix in this pr #4522

**Comment by ChengJie1053** [comment]
> pring @ChengJie1053 need to fix in this pr #4522

Ok, thank you for reviewing the code

**Review by peacewong — APPROVED** [review]
LGTM.

**Review by peacewong — APPROVED** [review]
LGTM.

**Pull request merged**
